name: Main
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache PNPm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm.lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0

      - name: Setup PNPm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.2
          run_install: true

      - name: Test Coverage
        run: |
          pnpm test:coverage

      - uses: codecov/codecov-action@v2
        with:
          flags: unittests
          fail_ci_if_error: true
          verbose: true

  test-e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache PNPm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm.lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0

      - name: Setup PNPm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.2
          run_install: true

      - name: Setup Playwright
        run: |
          npx playwright install

      - name: Test E2E
        run: |
          pnpm test:e2e

      - uses: codecov/codecov-action@v2
        with:
          flags: e2etests
          fail_ci_if_error: true
          verbose: true
          directory: ./.nyc_output/
